-- Active: 1671469511724@@127.0.0.1@3306@etvdb
DROP DATABASE IF EXISTS ETVDB;
CREATE DATABASE IF NOT EXISTS ETVDB; 

USE ETVDB;

CREATE TABLE `IDIOMES`(
    `ID_IDIOMA` INT NOT NULL AUTO_INCREMENT,
    `NOM_IDIOMA` VARCHAR(50) NOT NULL,
    PRIMARY KEY(`ID_IDIOMA`)
); 

CREATE TABLE `TIPUS`(
    `ID_TIPUS` INT NOT NULL AUTO_INCREMENT,
    `NOM_TIPUS` VARCHAR(50) NOT NULL,
    PRIMARY KEY(`ID_TIPUS`)
); 

CREATE TABLE `SERVEIS`(
    `ID_SERVEI` INT NOT NULL AUTO_INCREMENT,
    `NOM_SERVEI` VARCHAR(50) NOT NULL,
    PRIMARY KEY(`ID_SERVEI`)
); 

CREATE TABLE `VACANCES`(
    `ID_VACANCES` INT NOT NULL AUTO_INCREMENT,
    `NOM_VACANCES` VARCHAR(50) NOT NULL,
    PRIMARY KEY(`ID_VACANCES`)
); 

CREATE TABLE `TRADUCCIO_TIPUS`(
    `FK_ID_TIPUS` INT NOT NULL,
    `FK_ID_IDIOMA` INT NOT NULL,
    `TRADUCCIO_TIPUS` VARCHAR(50) NOT NULL,
    PRIMARY KEY(`FK_ID_TIPUS`, `FK_ID_IDIOMA`),
    FOREIGN KEY(`FK_ID_TIPUS`) REFERENCES `TIPUS`(`ID_TIPUS`),
    FOREIGN KEY(`FK_ID_IDIOMA`) REFERENCES `IDIOMES`(`ID_IDIOMA`)
); 

CREATE TABLE `TRADUCCIO_VACANCES`(
    `FK_ID_VACANCES` INT NOT NULL,
    `FK_ID_IDIOMA` INT NOT NULL,
    `TRADUCCIO_VAC` VARCHAR(50) NOT NULL,
    PRIMARY KEY(`FK_ID_VACANCES`, `FK_ID_IDIOMA`),
    FOREIGN KEY(`FK_ID_VACANCES`) REFERENCES `VACANCES`(`ID_VACANCES`),
    FOREIGN KEY(`FK_ID_IDIOMA`) REFERENCES `IDIOMES`(`ID_IDIOMA`)
); 

CREATE TABLE `TRADUCCIO_SERVEIS`(
    `FK_ID_SERVEI` INT NOT NULL,
    `FK_ID_IDIOMA` INT NOT NULL,
    `TRADUCCIO_SERVEI` VARCHAR(50) NOT NULL,
    PRIMARY KEY(`FK_ID_SERVEI`, `FK_ID_IDIOMA`),
    FOREIGN KEY(`FK_ID_SERVEI`) REFERENCES `SERVEIS`(`ID_SERVEI`),
    FOREIGN KEY(`FK_ID_IDIOMA`) REFERENCES `IDIOMES`(`ID_IDIOMA`)
); 

CREATE TABLE `MUNICIPIS`(
    `ID_MUNICIPI` INT NOT NULL AUTO_INCREMENT,
    `NOM_MUNICIPI` VARCHAR(50) NOT NULL,
    PRIMARY KEY(`ID_MUNICIPI`)
); 

CREATE TABLE `USUARIS`(
    `ID_USUARI` INT NOT NULL AUTO_INCREMENT,
    `DNI` VARCHAR(9) NOT NULL,
    `NOM_COMPLET` VARCHAR(50) NOT NULL,
    `CORREU_ELECTRONIC` VARCHAR(50) NOT NULL,
    `CONTRASENYA` VARCHAR(50) NOT NULL,
    `TELEFON` VARCHAR(9) NOT NULL,
    `ADMINISTRADOR` BOOLEAN NOT NULL,
    PRIMARY KEY(`ID_USUARI`)
); 

CREATE TABLE `CATEGORIA`(
    `ID_CATEGORIA` INT NOT NULL AUTO_INCREMENT,
    `NOM_CATEGORIA` VARCHAR(50) NOT NULL,
    `TARIFA` FLOAT NOT NULL,
    PRIMARY KEY(`ID_CATEGORIA`)
); 

CREATE TABLE `ALLOTJAMENTS`(
    `ID_ALLOTJAMENT` INT NOT NULL AUTO_INCREMENT,
    `NOM_COMERCIAL` VARCHAR(50) NOT NULL,
    `NUM_REGISTRE` VARCHAR(50) NOT NULL,
    `DESCRIPCIO` VARCHAR(500) NOT NULL,
    `LLITS` INT NOT NULL,
    `PERSONES` INT NOT NULL,
    `BANYS` INT NOT NULL,
    `FOTOGRAFIES` VARCHAR(50) NOT NULL,
    `ADREÇA` VARCHAR(50) NOT NULL,
    `DESTACAT` BOOLEAN NOT NULL,
    `VALORACIO_GLOBAL` INT NOT NULL,
    `FK_ID_MUNICIPI` INT NOT NULL,
    `FK_ID_TIPUS` INT NOT NULL,
    `FK_ID_SERVEI` INT NOT NULL,
    `FK_ID_VACANCES` INT NOT NULL,
    `FK_ID_CATEGORIA` INT NOT NULL,
    `FK_ID_USUARI` INT NOT NULL,
    PRIMARY KEY(`ID_ALLOTJAMENT`),
    FOREIGN KEY(`FK_ID_MUNICIPI`) REFERENCES `MUNICIPIS`(`ID_MUNICIPI`),
    FOREIGN KEY(`FK_ID_TIPUS`) REFERENCES `TIPUS`(`ID_TIPUS`),
    FOREIGN KEY(`FK_ID_SERVEI`) REFERENCES `SERVEIS`(`ID_SERVEI`),
    FOREIGN KEY(`FK_ID_VACANCES`) REFERENCES `VACANCES`(`ID_VACANCES`),
    FOREIGN KEY(`FK_ID_CATEGORIA`) REFERENCES `CATEGORIA`(`ID_CATEGORIA`),
    FOREIGN KEY(`FK_ID_USUARI`) REFERENCES `USUARIS`(`ID_USUARI`)
); 

CREATE TABLE `RESERVA`(
    `ID_RESERVA` INT NOT NULL AUTO_INCREMENT,
    `FK_ID_USUARI` INT NOT NULL,
    `FK_ID_ALLOTJAMENT` INT NOT NULL,
    `DATA_INICIAL` DATE NOT NULL,
    `DATA_FINAL` DATE NOT NULL,
    `CONFIRMADA` BOOLEAN NOT NULL,
    PRIMARY KEY(`ID_RESERVA`),
    FOREIGN KEY(`FK_ID_USUARI`) REFERENCES `USUARIS` (`ID_USUARI`),
    FOREIGN KEY(`FK_ID_ALLOTJAMENT`) REFERENCES `ALLOTJAMENTS` (`ID_ALLOTJAMENT`)
); 

CREATE TABLE `COMENTARIS`(
    `ID_COMENTARI` INT NOT NULL AUTO_INCREMENT,
    `DESCRIPCIO` VARCHAR(500) NOT NULL,
    `DATA` DATE NOT NULL,
    `HORA` TIME NOT NULL,
    `FK_ID_USUARI` INT NOT NULL,
    `FK_ID_ALLOTJAMENT` INT NOT NULL,
    PRIMARY KEY(`ID_COMENTARI`),
    FOREIGN KEY(`FK_ID_USUARI`) REFERENCES `USUARIS`(`ID_USUARI`),
    FOREIGN KEY(`FK_ID_ALLOTJAMENT`) REFERENCES `ALLOTJAMENTS`(`ID_ALLOTJAMENT`)
); 

CREATE TABLE `VALORACIONS`(
    `ID_VALORACIO` INT NOT NULL AUTO_INCREMENT,
    `PUNTUACIO` INT NOT NULL,
    `FK_ID_USUARI` INT NOT NULL,
    `FK_ID_ALLOTJAMENT` INT NOT NULL,
    PRIMARY KEY(`ID_VALORACIO`),
    FOREIGN KEY(`FK_ID_USUARI`) REFERENCES `USUARIS`(`ID_USUARI`),
    FOREIGN KEY(`FK_ID_ALLOTJAMENT`) REFERENCES `ALLOTJAMENTS`(`ID_ALLOTJAMENT`)
); 

CREATE TABLE `ALLOTJAMENTS_SERVEIS`(
    `FK_ID_ALLOT` INT NOT NULL,
    `FK_ID_SERVEI` INT NOT NULL,
    PRIMARY KEY(`FK_ID_ALLOT`, `FK_ID_SERVEI`),
    FOREIGN KEY(`FK_ID_ALLOT`) REFERENCES `ALLOTJAMENTS`(`ID_ALLOTJAMENT`),
    FOREIGN KEY(`FK_ID_SERVEI`) REFERENCES `SERVEIS`(`ID_SERVEI`)
);

CREATE TRIGGER `CALCULAR_VALORACIO_GLOBAL` AFTER INSERT ON `VALORACIONS` FOR EACH ROW
BEGIN
    UPDATE ALLOTJAMENTS SET VALORACIO_GLOBAL = (SELECT AVG(PUNTUACIO) FROM VALORACIONS WHERE FK_ID_ALLOTJAMENT = NEW.FK_ID_ALLOTJAMENT) WHERE ID_ALLOTJAMENT = NEW.FK_ID_ALLOTJAMENT;
END;