-- ! INSERTS

INSERT INTO `IDIOMES` (`ID_IDIOMA`, `NOM_IDIOMA`) VALUES
    (1, "ESPANYOL"),
    (2,"CATALA"),
    (3,"ANGLES");

INSERT INTO `TIPUS`(`NOM_TIPUS`) VALUES
	('Hotel'),
	('Apartament'),
	('Casa Rural'),
	('Hostal'),
	('Camping'),
	('Piscina'),
	('Restaurant'),
	('Bar'),
	('Gimnas'),
	('Spa');

INSERT INTO `MUNICIPIS` (`ID_MUNICIPI`, `NOM_MUNICIPI`) VALUES
	(1, 'Alaior'),
	(2, 'Alaró'),
	(3, 'Alcúdia'),
	(4, 'Algaida'),
	(5, 'Andratx'),
	(6, 'Ariany'),
	(7, 'Artà'),
	(8, 'Banyalbufar'),
	(9, 'Binissalem'),
	(10, 'Búger'),
	(11, 'Bunyola'),
	(12, 'Calvià'),
	(13, 'Campanet'),
	(14, 'Campos'),
	(15, 'Capdepera'),
	(16, 'es Castell'),
	(17, 'Ciutadella de Menorca'),
	(18, 'Consell'),
	(19, 'Costitx'),
	(20, 'Deià'),
	(21, 'Eivissa'),
	(22, 'Escorca'),
	(23, 'Esporles'),
	(24, 'Estellencs'),
	(25, 'Felanitx'),
	(26, 'Ferreries'),
	(27, 'Formentera'),
	(28, 'Fornalutx'),
	(29, 'Inca'),
	(30, 'Lloret de Vistalegre'),
	(31, 'Lloseta'),
	(32, 'Llubí'),
	(33, 'Llucmajor'),
	(34, 'Maó'),
	(35, 'Manacor'),
	(36, 'Mancor de la Vall'),
	(37, 'Maria de la Salut'),
	(38, 'Marratxí'),
	(39, 'Es Mercadal'),
	(40, 'Es Migjorn Gran'),
	(41, 'Montuïri'),
	(42, 'Muro'),
	(43, 'Palma'),
	(44, 'Petra'),
	(45, 'Sa Pobla'),
	(46, 'Pollença'),
	(47, 'Porreres'),
	(48, 'Puigpunyent'),
	(49, 'Ses Salines'),
	(50, 'Sant Antoni de Portmany'),
	(51, 'Sant Joan'),
	(52, 'Sant Joan de Labritja'),
	(53, 'Sant Josep de sa Talaia'),
	(54, 'Sant Llorenç des Cardassar'),
	(55, 'Sant Lluís'),
	(56, 'Santa Eugènia'),
	(57, 'Santa Eulària des Riu'),
	(58, 'Santa Margalida'),
	(59, 'Santa Maria del Camí'),
	(60, 'Santanyí'),
	(61, 'Selva'),
	(62, 'Sencelles'),
	(63, 'Sineu'),
	(64, 'Sóller'),
	(65, 'Son Servera'),
	(66, 'Valldemossa'),
	(67, 'Vilafranca de Bonany');